In [1]:
import numpy as np

In [2]:
import pandas as pd

In [11]:
X = np.random.random((5,5))

In [12]:
X

array([[0.88926989, 0.59048054, 0.95779149, 0.12650069, 0.13557133],
       [0.84085405, 0.01732873, 0.69196949, 0.43545266, 0.34995356],
       [0.03246682, 0.93782601, 0.3225311 , 0.39342405, 0.41017881],
       [0.77439697, 0.17270187, 0.94463554, 0.91295121, 0.17657209],
       [0.18051196, 0.86189852, 0.97955386, 0.11052633, 0.40523099]])

In [15]:
mean1 = X.mean()

In [16]:
mean1

np.float64(0.506023143106527)

In [17]:
std1 = X.std()

In [18]:
std1

np.float64(0.3342764516977828)

In [19]:
Z = (X-mean1)/std1

In [20]:
Z

array([[ 1.14649641,  0.25265735,  1.35148122, -1.13535504, -1.10821989],
       [ 1.00165868, -1.46194686,  0.55626517, -0.21111414, -0.46688775],
       [-1.41666073,  1.29175376, -0.54892304, -0.33684422, -0.28672175],
       [ 0.80284994, -0.99714254,  1.31212472,  1.21733992, -0.98556466],
       [-0.97377839,  1.06461397,  1.41658413, -1.18314291, -0.30152334]])

In [40]:
np.save("X_normalized.npy", Z)


In [32]:
Y = np.arange(1,101,1)

In [33]:
Y


array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [36]:
Y1=Y.reshape(10,10)**2

In [37]:
Y1

array([[    1,     4,     9,    16,    25,    36,    49,    64,    81,
          100],
       [  121,   144,   169,   196,   225,   256,   289,   324,   361,
          400],
       [  441,   484,   529,   576,   625,   676,   729,   784,   841,
          900],
       [  961,  1024,  1089,  1156,  1225,  1296,  1369,  1444,  1521,
         1600],
       [ 1681,  1764,  1849,  1936,  2025,  2116,  2209,  2304,  2401,
         2500],
       [ 2601,  2704,  2809,  2916,  3025,  3136,  3249,  3364,  3481,
         3600],
       [ 3721,  3844,  3969,  4096,  4225,  4356,  4489,  4624,  4761,
         4900],
       [ 5041,  5184,  5329,  5476,  5625,  5776,  5929,  6084,  6241,
         6400],
       [ 6561,  6724,  6889,  7056,  7225,  7396,  7569,  7744,  7921,
         8100],
       [ 8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,  9801,
        10000]])

In [38]:
div = Y1[Y1 % 3 ==0]

In [39]:
div

array([   9,   36,   81,  144,  225,  324,  441,  576,  729,  900, 1089,
       1296, 1521, 1764, 2025, 2304, 2601, 2916, 3249, 3600, 3969, 4356,
       4761, 5184, 5625, 6084, 6561, 7056, 7569, 8100, 8649, 9216, 9801])

In [41]:
np.save("div_by_3.npy", div)